# -*- coding: utf-8 -*-
"""PhoData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17En-2oJD5QTwe0cRCd6yFck6dlWmS91x
"""

import pandas as pd
import matplotlib.pyplot as plt
import sqlite3
import json

df = pd.read_csv('PHoData3.0_final_adjusted.csv')

df

#Data clean



df['Day Of Week'] = df['Day Of Week'].replace('Thuesday', 'Thursday')

#sql


connection = sqlite3.connect('pho_database.db')


df.to_sql('pho_data', connection, if_exists='replace', index=False)



cursor = connection.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())



query = "SELECT * FROM pho_data WHERE `Day Of Week` = 'Monday'"
result = pd.read_sql_query(query, connection)

# Display the result
result

import pandas as pd
import matplotlib.pyplot as plt
import sqlite3

# Load the dataset
df = pd.read_csv('PHoData3.0_final_adjusted.csv')

# Fix misspelled weekday name
df['Day Of Week'] = df['Day Of Week'].replace('Thuesday', 'Thursday')

# Connect to SQLite database
connection = sqlite3.connect('pho_database.db')

# Save DataFrame to SQL
df.to_sql('pho_data', connection, if_exists='replace', index=False)

# Verify tables
cursor = connection.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

# Query data for a specific day
query = "SELECT * FROM pho_data WHERE `Day Of Week` = 'Monday'"
result = pd.read_sql_query(query, connection)

# Display the result
print(result)

# Ensure timestamps are parsed correctly
df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce')

# Group by existing "Hour of Visit" (without overwriting)
customer_count_by_hour = df.groupby('Hour of Visit').size()

# Plot customer count by hour
plt.figure(figsize=(20, 12))
plt.bar(customer_count_by_hour.index, customer_count_by_hour.values)
plt.xlabel('Hour of Day')
plt.ylabel('Number of Customers')
plt.title('Customer Count by Time of Day')
plt.xticks(ticks=range(0, 24))
plt.grid(axis='y', alpha=0.7)
plt.show()

# Plot customer count by day of the week
customer_count_by_day = df.groupby('Day Of Week').size()

plt.figure(figsize=(20, 12))
plt.bar(customer_count_by_day.index, customer_count_by_day.values)
plt.xlabel('Day of Week')
plt.ylabel('Number of Customers')
plt.title('Customer Count by Day of the Week')
plt.show()

import pandas as pd
import urllib.request
import json
from datetime import datetime, timedelta

# Loaddataset
df = pd.read_csv('PHoData3.0.csv')

# Convert 'Timestamp' to datetime and extract the date
df['Date'] = pd.to_datetime(df['Timestamp']).dt.date

# API setup
API_KEY = getpass.getpass("7DR4NHN6A8B7H42UHUDQZVR7M")
BASE_URL = "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/"
LOCATION = "20D Montgomery Village Avenue, Gaithersburg, MD 20879"

# Calculate the date 30 days ago
thirty_days_ago = datetime.now().date() - timedelta(days=30)

# Filter unique dates within the past 30 days
unique_dates = df['Date'].unique()
past_30_days_dates = [date for date in unique_dates if thirty_days_ago <= date <= datetime.now().date()]

# Initialize a dictionary to store rain data
rain_data = {}

# Function to fetch rain status for a single date
def fetch_rain_status(date, location, api_key):
    try:
        # Encode the location and build the API URL
        encoded_location = urllib.parse.quote(location)
        url = f"{BASE_URL}{encoded_location}/{date}?unitGroup=metric&key={api_key}&contentType=json"

        # Make the request
        result_bytes = urllib.request.urlopen(url)

        # Parse the response
        json_data = json.load(result_bytes)

        # Check for precipitation
        if 'days' in json_data and 'precip' in json_data['days'][0]:
            return 'Yes' if json_data['days'][0]['precip'] > 0 else 'No'
        else:
            return None
    except urllib.error.HTTPError as e:
        error_info = e.read().decode()
        print(f"HTTP Error for {date}: {e.code} - {error_info}")
        return None
    except urllib.error.URLError as e:
        print(f"URL Error for {date}: {e.reason}")
        return None
    except Exception as e:
        print(f"Unexpected error for {date}: {str(e)}")
        return None

# Fetch rain data for each valid date
for date in past_30_days_dates:
    rain_data[date] = fetch_rain_status(date, LOCATION, API_KEY)

# Map the rain data to the dataset; leave future dates and older dates as NaN
df['Rain2.0'] = df['Date'].apply(lambda date: rain_data.get(date, None) if date in past_30_days_dates else None)

# Save the updated dataset
df.to_csv('PHoData3.0_with_Rain2.0.csv', index=False)

print("New column 'Rain2.0' added successfully!")

import pandas as pd
import urllib.request
import json
import time
from datetime import datetime, timedelta

# Load dataset
file_path = "/mnt/data/PHoData3.0_with_Rain2.0.csv"
df = pd.read_csv("PHoData3.0.csv")

# Convert 'Timestamp' to datetime and extract the date
df['Date'] = pd.to_datetime(df['Timestamp']).dt.date

# API setup
API_KEY = "7DR4NHN6A8B7H42UHUDQZVR7M"
BASE_URL = "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/"
LOCATION = "20D Montgomery Village Avenue, Gaithersburg, MD 20879"

# Get unique dates in the dataset
unique_dates = df['Date'].unique()

# Initialize dictionary to store rain data
rain_data = {}

# Function to fetch rain status
def fetch_rain_status(date, location, api_key):
    try:
        encoded_location = urllib.parse.quote(location)
        url = f"{BASE_URL}{encoded_location}/{date}?unitGroup=metric&key={api_key}&contentType=json"

        # Make request
        result_bytes = urllib.request.urlopen(url)
        json_data = json.load(result_bytes)

        # Check precipitation
        if 'days' in json_data and 'precip' in json_data['days'][0]:
            return 'Yes' if json_data['days'][0]['precip'] > 0 else 'No'
        else:
            return None
    except urllib.error.HTTPError as e:
        print(f"HTTP Error for {date}: {e.code}")
        return None
    except urllib.error.URLError as e:
        print(f"URL Error for {date}: {e.reason}")
        return None
    except Exception as e:
        print(f"Unexpected error for {date}: {str(e)}")
        return None

# Fetch rain data for each unique date
for date in unique_dates:
    if pd.notna(date):  # Ensure date is valid
        rain_data[date] = fetch_rain_status(date, LOCATION, API_KEY)
        time.sleep(2)  # Short delay to avoid API rate limits

# Update 'Rained' column based on API response
df['Rained'] = df['Date'].map(rain_data)

# Save updated dataset
updated_file_path = "/mnt/data/PHoData3.0_with_Rain2.0_Updated.csv"
df.to_csv("PHoData3.0_with_Rain2.0_Updated.csv", index=False)

print(f"✅ Rain data updated and saved as: {updated_file_path}")

import pandas as pd
import matplotlib.pyplot as plt

# Load the dataset
file_path = "PHoData3.0_with_Rain2.0_Updated.csv"  # Update with your file path
df = pd.read_csv(file_path)

# Group by "Rained" and sum the "Party Size" to get total customers
customer_rain_analysis = df.groupby("Rained")["Party Size"].sum().reset_index()

# Rename columns for clarity
customer_rain_analysis.columns = ["Rained", "Total Customers"]

# Create the bar chart
plt.figure(figsize=(8, 5))
plt.bar(customer_rain_analysis["Rained"], customer_rain_analysis["Total Customers"], color=["blue", "gray"])
plt.xlabel("Rained")
plt.ylabel("Total Customers")
plt.title("Total Customers on Rainy vs. Non-Rainy Days")
plt.show()